// Code generated by "stringer -type=DeviceState"; DO NOT EDIT

package adb


func (s DeviceState) String() string {
	switch DeviceState(s) {
	case StateDisconnected:
		return "Disconnect"
	case StateOffline:
		return "Offline"
	case StateOnline:
		return "Online"
	case StateUnauthorized:
		return "Unauthorized"
	case StateAuthorizing:
		return "Authorizing"
	case StateRecovery:
		return "Recovery"
	default:
		return "Unknown"
	}
}